---
- name: Chocolatey install multiple
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false
  vars:
    choco_packages:
      - name: nodejs
      - name: python
  tasks:
    - name: Install specific versions of packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: present
      loop: "{{ choco_packages }}"

    - name: Check python version
      ansible.windows.win_command: python --version
      register: check_python_version
      changed_when: false

    - name: Check nodejs version
      ansible.windows.win_command: node --version
      register: check_node_version
      changed_when: false

    - name: Print message
      ansible.builtin.debug:
        msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}
