---
- name: Chocolatey install specific
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false

  tasks:
    - name: Install choco package with specific version
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ package_name }}"
