---
- name: "Get list of files inside {{ filetree_controller_credentials }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_credentials }}"
    file_type: file
    recurse: true
  register: __list_files_controller_credentials

- name: "Read Credentials definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_credentials_definitions_item.path }}"
  loop: "{{ __list_files_controller_credentials.files }}"
  loop_control:
    loop_var: __read_credentials_definitions_item
  register: __contents_filetree_controller_credentials

- name: "Populate Credentials list"
  ansible.builtin.set_fact:
    __populate_controller_credentials: "{{ (__populate_controller_credentials | default([])) + __populate_credentials_list_item.ansible_facts.controller_credentials }}"
  loop: "{{ __contents_filetree_controller_credentials.results }}"
  loop_control:
    loop_var: __populate_credentials_list_item
  when: __contents_filetree_controller_credentials.results is defined and __populate_credentials_list_item.ansible_facts.controller_credentials is defined

- name: "Segregated Credentials list when controller_location is defined"
  when: controller_location is defined and __populate_controller_credentials is defined
  block:
    - name: "Populate Credentials list by _common objects"
      ansible.builtin.set_fact:
        __populate_controller_credentials_common: "{{ (__populate_controller_credentials_common | default([])) + [__populate_credentials_list_common_item] }}"
      loop: "{{ __populate_controller_credentials }}"
      loop_control:
        loop_var: __populate_credentials_list_common_item
      when: "__populate_credentials_list_common_item.controller_location is not defined"

    - name: "Populate Credentials list by __site objects"
      ansible.builtin.set_fact:
        __populate_controller_credentials_site: "{{ (__populate_controller_credentials_site | default([])) + [__populate_credentials_list_site_item] }}"
      loop: "{{ __populate_controller_credentials }}"
      loop_control:
        loop_var: __populate_credentials_list_site_item
      when: "__populate_credentials_list_site_item.controller_location is defined and __populate_credentials_list_site_item.controller_location == controller_location"

    - name: "Concatenate Credentials list common + site"
      ansible.builtin.set_fact:
        __populate_controller_credentials_total: "{{ __populate_controller_credentials_common | default([]) + __populate_controller_credentials_site }}"
      when: __populate_controller_credentials_site is defined

    - name: "Set Credentials Data Structure common + site concatenated"
      ansible.builtin.set_fact:
        __populate_controller_credentials: "{{ __populate_controller_credentials_total }}"
      when: __populate_controller_credentials_total is defined

- name: "Set Credentials Data Structure"
  ansible.builtin.set_fact:
    controller_credentials: "{{ __populate_controller_credentials }}"
  when: __populate_controller_credentials is defined
...
