---
- name: "Get list of files inside {{ filetree_controller_inventories }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_inventories }}"
    file_type: file
    recurse: true
  register: __list_files_controller_inventories

- name: "Read Inventories definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_inventories_definitions_item.path }}"
  loop: "{{ __list_files_controller_inventories.files }}"
  loop_control:
    loop_var: __read_inventories_definitions_item
  register: __contents_filetree_controller_inventories

- name: "Populate Inventories list"
  ansible.builtin.set_fact:
    __populate_controller_inventories: "{{ (__populate_controller_inventories | default([])) + __populate_inventories_list_item.ansible_facts.controller_inventories }}"
  loop: "{{ __contents_filetree_controller_inventories.results }}"
  loop_control:
    loop_var: __populate_inventories_list_item
  when: __contents_filetree_controller_inventories.results is defined and __populate_inventories_list_item.ansible_facts.controller_inventories is defined

- name: "Set Inventories Data Structure"
  ansible.builtin.set_fact:
    controller_inventories: "{{ __populate_controller_inventories }}"
  when: __populate_controller_inventories is defined
...
