---
- name: "Get list of files inside {{ filetree_controller_templates }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_templates }}"
    file_type: file
    recurse: true
  register: __list_files_controller_templates

- name: "Read Job Templates definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_job_templates_definitions_item.path }}"
  loop: "{{ __list_files_controller_templates.files }}"
  loop_control:
    loop_var: __read_job_templates_definitions_item
  register: __contents_filetree_controller_templates

- name: "Populate Job Templates list"
  ansible.builtin.set_fact:
    __populate_controller_job_templates: "{{ (__populate_controller_job_templates | default([])) + __populate_job_templates_list_item.ansible_facts.controller_templates }}"
  loop: "{{ __contents_filetree_controller_templates.results }}"
  loop_control:
    loop_var: __populate_job_templates_list_item
  when: __contents_filetree_controller_templates.results is defined and __populate_job_templates_list_item.ansible_facts.controller_templates is defined

- name: "Set Job Templates Data Structure"
  ansible.builtin.set_fact:
    controller_templates: "{{ __populate_controller_job_templates }}"
  when: __populate_controller_job_templates is defined
...
