---
- name: "Get list of files inside {{ filetree_controller_labels }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_labels }}"
    file_type: file
    recurse: true
  register: __list_files_controller_labels

- name: "Read Labels definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_labels_definitions_item.path }}"
  loop: "{{ __list_files_controller_labels.files }}"
  loop_control:
    loop_var: __read_labels_definitions_item
  register: __contents_filetree_controller_labels

- name: "Populate Labels list"
  ansible.builtin.set_fact:
    __populate_controller_labels: "{{ (__populate_controller_labels | default([])) + __populate_labels_list_item.ansible_facts.controller_labels }}"
  loop: "{{ __contents_filetree_controller_labels.results }}"
  loop_control:
    loop_var: __populate_labels_list_item
  when: __contents_filetree_controller_labels.results is defined and __populate_labels_list_item.ansible_facts.controller_labels is defined

- name: "Set Labels Data Structure"
  ansible.builtin.set_fact:
    controller_labels: "{{ __populate_controller_labels }}"
  when: __populate_controller_labels is defined
...
