---
# tasks file for controller_credentials
- name: Get the organization ID
  ansible.builtin.set_fact:
    __controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                              query_params={'name': orgs},
                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                   }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Get the API list of all Credentials in Organization {{ orgs }}"
  ansible.builtin.set_fact:
    __controller_api_credentials: "{{ query(controller_api_plugin, 'credentials',
                                            query_params={'organization': __controller_organization_id.id},
                                            host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                            return_all=true, max_objects=query_controller_api_max_objects)
                                   }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Find the difference of Credentials between what is on the Controller versus CasC on SCM"
  ansible.builtin.set_fact:
    __credentials_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                          api_list=__controller_api_credentials, compare_list=controller_credentials,
                                          with_present=false, set_absent=true)
                               }}"

- name: "Set credential's list to be configured"
  ansible.builtin.set_fact:
    controller_credentials: "{{ __credentials_difference }}"
...
