---
- name: "Get the current controller user to determine if it is super-admin"
  ansible.builtin.set_fact:
    __controller_api_current_user_check_is_admin: "{{ lookup(controller_api_plugin, 'users',
                                                              query_params={'username': controller_username},
                                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                                   }}"
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"

- name: "Team differences (block)"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
  block:
    - name: Get the organization ID
      ansible.builtin.set_fact:
        __controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations',
                                                  query_params={'name': orgs},
                                                  host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs)
                                       }}"
      no_log: "{{ controller_configuration_object_diff_secure_logging }}"

    - name: "Get the API list of all teams in Organization {{ orgs }}"
      ansible.builtin.set_fact:
        __controller_api_teams: "{{ query(controller_api_plugin, 'teams',
                                          query_params={'organization': __controller_organization_id.id},
                                          host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                          return_all=true, max_objects=query_controller_api_max_objects)
                                 }}"
      no_log: "{{ controller_configuration_object_diff_secure_logging }}"

    - name: "Find the difference of Teams between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __teams_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                        api_list=__controller_api_teams,
                                        compare_list=controller_teams,
                                        with_present=false,
                                        set_absent=true)
                             }}"

    - name: "Sets the difference of Teams between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        controller_teams: "{{ __teams_difference }}"
...
