download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/chocolatey-chocolatey-1.5.1.tar.gz
format_version: 1.0.0
name: chocolatey
namespace: chocolatey
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2023-07-11T16:01:38.819042Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIcBAABCAAGBQJkrXzXAAoJEOGkvXCKgoqtNGoP/3I1CHXcdfgQYzfHqyh30uMV

    P0oQlXWttm1ZpjPdOTwuYGsMj1KytPjZovwJwogVbvuHH+Se6hRCJ5vxVT5LMCi7

    bsUY88C3KMD2bAHprfhgceCPNzkkuvIKHEZUa+iwDhZpsanCzarxvSU4sp80HOA4

    WxFCmGJttLBPHX2FHaGjwmKNol8sIi0UoNzI6TOqSHX8hDXfA/jGhtMZ0cYtPRf0

    +kNg5nGLYgvTenf6DTVvSZyHTeETMjDVHV6BzGKT7zxniwn1biGDjd354RnVgEb/

    bLoQnZJhLEoc6jgQ6+dQlFsd+Gv345zzIoQEegc2nHZCdkKHImO0pBt//MCLJcGd

    X0vq4iwiu7tY8RmT43gqB6Lsc0YH4E1ouCzb2omd9T09hDuj5DnJyGEtG0S4sFJI

    IeLWFeXSV+arqyWwBQFWnXIkap3ZfbUCcNVDml4nL+Km/cZY8Xaj2x6TJmemqQ+R

    fZhWzPkWsP5iG0BercoIFJjdtGZOtCECGe7IUDJhPhEF9vC+9TMLPyMKW41f9Gfs

    mO9Xtdm6w0tskHhcmwWyqSwCuCjdNb8GvwOCCws03wgKs3OxKh78JNnGa+tuXPzn

    h+JtBOnUeBHlA/axsYH3lTg7hIb3Rg9ApcLgy16FNBGbIrj4peVQsnfOZzOEgWaP

    Es21kik5LhKMVQckrIjF

    =HOBJ

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 1.5.1
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/chocolatey/chocolatey/versions/1.5.1/
