download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/redhat-rhel_system_roles-1.20.0.tar.gz
format_version: 1.0.0
name: rhel_system_roles
namespace: redhat
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2022-09-23T22:44:20.030749Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIVAwUAYy42wOGkvXCKgoqtAQhZORAAn8Mh+YD3jZAHNNb25Vo9oK45OeqrrGzE

    SOUB0ENPRjTlCD/cwiMBnQB6zidR6iS6qW/DrpEWOVGpaQ6QxGxOpo4YyBaqu2gX

    YaNM5lk6zK+dEVCRlEyL3+flLTSuEllooo6h8pk3tSsda9CcX/B6qf4Ocz59PNu+

    CYMejX+JVaFQ6504tf83bWXqBuujvwRcQM3CapaVglLbHLuWcZwLOeukP9cL66rN

    hsDcELUj8jrXKgZOtbg/xoD+OjwHODbnHoZbckowwsoUFozZAfF90AAMUzI9/qVw

    L/vZCYbMs+twanhpJwGtq6JfsU+H07I0KmKEcaIAby8OWMGBnwo2EIYLh38EGm7n

    19CPI+tnjqDz9onbaRC+LoUBX9kKQV5CZs5i5rGufpYQg5qUCEeCVKqfwK83+Aa2

    9IoOz6SZ3JNba7KLtMiga6JXx4j84lJezuanXTLLiKW+Q2GUDnIIYPxrIrh+gK5c

    Lx6LsOf3QAAw/MP9ABXVNXG/NmXOCj+4QfcrvYA8k+/nh7lVORTQtnMa5Z9MNysd

    lNzAKdUnY6cov9EXchml0N/Y6C55SwDKg2fz/zNlOCWyAfgaaD8V9GiqLlKlBOtj

    jButntWCILn8soRdQ5bua3LR2bv9mO5dghhbFp4GKPnCHXevE4ZWEKA+KavUOQby

    a1gYOR/jMnQ=

    =eVuv

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 1.20.0
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/redhat/rhel_system_roles/versions/1.20.0/
