download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/redhat-satellite-3.8.0.tar.gz
format_version: 1.0.0
name: satellite
namespace: redhat
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2023-01-13T18:30:31.140299Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIVAwUAY8GjReGkvXCKgoqtAQjb6hAAjG+JyoEDeP7Sgz8O/dnZt1smlX/JSznQ

    /TmM1huU3m6B+7NY4FVP/0NOsd2rxlyTW1TOx8dd7u1FyPPgwZxRhdCJu7O2+FJk

    r0wjrzhLMWrozehAiL+0iAFe9A7DFlbL3Tt+iRvZqbyhu9oHB1SbT+8rm2nQXTji

    Rpiga0+71goLasjIbFphDckoTA9udVEz89KPTvzI/InJ6AgJ3hDXlZPni8iQF6MJ

    SNy0F5MIqaMcYT6bkFPRcGovOzpOSsISqhaQH0xzv2uLtw3NtP3zZkrM3d6m0xmU

    a5+IW+Ejxcy2+aMUSc6jGRy8MNhgANX/em2XoHJneqWdTXAgJ10DQn4Xml8d/qSO

    LhSQPIgEZ2aUfdrARpEdTcCjsfqBJsQXp9yOWDEKQSusN0o+zM2NlVpDOPG+qob7

    ZIklQAM0c4aZ8tQ6aDjuK+iVwfuvUs2rwDH4nvIciZhL0hdolzcXenvZpN2TfZIO

    rmLev5mJYKCiX3X2va8y3kq+DFi6qaYYLtiMZJoqbPIQ+k8S1t9UHIK8l9w/Xsac

    im8LoS0yzaU+nSocAqoWZ30Jmef6kaUKJQPCQjprVM9HRoyyk37ZsiJPO3ETUR9W

    W0J+iurKg5CMJcKvu1EEIKzKlrfV/EipDX/OPxvpofRVEQVbDiNqwaWiU3BonxCd

    lyF901TBRRM=

    =Npnv

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 3.8.0
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/redhat/satellite/versions/3.8.0/
