---
satellite_content_views:
  # Red Hat Enterprise Linux 7
  - name: RHEL7
    content_view: RHEL7
    repositories:
      - name: Red Hat Enterprise Linux 7 Server (RPMs)
        basearch: x86_64
        releasever: 7Server
        product: 'Red Hat Enterprise Linux Server'
      - name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
        basearch: x86_64
        product: 'Red Hat Enterprise Linux Server'
      - name: Red Hat Satellite Tools 6.8 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
        product: 'Red Hat Enterprise Linux Server'
  # Red Hat Enterprise Linux 8
  - name: RHEL8
    content_view: RHEL8
    content_view_update: true
    repositories:
      - name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
        releasever: 8
        product: Red Hat Enterprise Linux for x86_64
      - name: Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
        releasever: 8
        product: Red Hat Enterprise Linux for x86_64
      - name: Red Hat Satellite Tools 6.8 for RHEL 8 x86_64 (RPMs)
        product: Red Hat Enterprise Linux for x86_64
