---
# defaults file for casc_implementation

# Organization and Environment Variables
orgs: "Acme"
dir_orgs_vars: orgs_vars
env: dev

# Controller lists

controller_settings: []
controller_organizations: []
controller_labels: []
controller_user_accounts: []
controller_teams: []
controller_credential_types: []
controller_credentials: []
controller_credential_input_sources: []
controller_notifications: []
controller_projects: []
controller_execution_environments: []
controller_applications: []
controller_inventories: []
controller_inventory_sources: []
controller_instance_groups: []
controller_hosts: []
controller_groups: []
controller_templates: []
controller_workflows: []
controller_schedules: []
controller_roles: []

# Controller Directory Path
filetree_controller_settings: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_settings.d/"
filetree_controller_organizations: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_organizations.d/"
filetree_controller_labels: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_labels.d/"
filetree_controller_user_accounts: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_users.d/"
filetree_controller_teams: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_teams.d/"
filetree_controller_credential_types: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_types.d/"
filetree_controller_credentials: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_credentials.d/"
filetree_controller_credential_input_sources: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_credential_input_sources.d/"
filetree_controller_notifications: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_notification_templates.d/"
filetree_controller_projects: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_projects.d/"
filetree_controller_execution_environments: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_execution_environments.d/"
filetree_controller_applications: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_applications.d/"
filetree_controller_inventories: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_inventories.d/"
filetree_controller_inventory_sources: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_inventory_sources.d/"
filetree_controller_instance_groups: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_instance_groups.d/"
filetree_controller_hosts: "{{ dir_orgs_vars }}/{{ orgs }}/env/{{ env }}/controller_hosts.d/"
filetree_controller_groups: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_groups.d/"
filetree_controller_templates: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_job_templates.d/"
filetree_controller_workflow_job_templates: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_workflow_job_templates.d/"
filetree_controller_schedules: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_schedules.d/"
filetree_controller_roles: "{{ dir_orgs_vars }}/{{ orgs }}/env/common/controller_roles.d/"

# filetree_read tasks order and name
controller_configuration_filetree_read_tasks:
  - {name: settings, var: controller_settings, tags: settings}
  - {name: organizations, var: controller_organizations, tags: organizations}
  - {name: labels, var: controller_labels, tags: labels}
  - {name: user_accounts, var: controller_user_accounts, tags: users}
  - {name: teams, var: controller_teams, tags: teams}
  - {name: credential_types, var: controller_credential_types, tags: credential_types}
  - {name: credential_input_sources, var: controller_credential_input_sources, tags: credential_input_sources}
  - {name: credentials, var: controller_credentials, tags: credentials}
  - {name: notifications, var: controller_notifications, tags: notification_templates}
  - {name: projects, var: controller_projects, tags: projects}
  - {name: execution_environments, var: controller_execution_environments, tags: execution_environments}
  - {name: applications, var: controller_applications, tags: applications}
  - {name: inventories, var: controller_inventories, tags: inventories}
  - {name: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
  - {name: instance_groups, var: controller_instance_groups, tags: instance_groups}
  - {name: hosts, var: controller_hosts, tags: hosts}
  - {name: groups, var: controller_groups, tags: inventories}
  - {name: job_templates, var: controller_templates, tags: job_templates}
  - {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
  - {name: schedules, var: controller_schedules, tags: schedules}
  - {name: roles, var: controller_roles, tags: roles}
...
