---
- name: "Check if the connection is to an Ansible Tower or to Automation Platform"
  ansible.builtin.set_fact:
    is_aap: "{{ lookup(controller_api_plugin, 'ping',
                       host=controller_hostname, oauth_token=controller_oauthtoken,
                       verify_ssl=controller_validate_certs).version is version('4.0.0', '>=') }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: Include tasks (block)
  when: "['all', 'labels', 'applications', 'instance_groups', 'settings', 'inventory', 'credentials', 'credential_types', 'notification_templates', 'users', 'teams', 'organizations', 'projects', 'execution_environments', 'job_templates', 'workflow_job_templates', 'workflow_job_template_nodes'] | intersect(input_tag) | length > 0"
  block:
    - name: "Export Inventories and related Groups and Hosts"
      ansible.builtin.include_tasks: "inventory.yml"
      when: "'inventory' in input_tag or 'all' in input_tag"
    - name: "Export Credentials"
      ansible.builtin.include_tasks: "credentials.yml"
      when: "'credentials' in input_tag or 'all' in input_tag"
    - name: "Export Credential Types"
      ansible.builtin.include_tasks: "credential_types.yml"
      when: "'credential_types' in input_tag or 'all' in input_tag"
    - name: "Export Notification Templates"
      ansible.builtin.include_tasks: "notification_templates.yml"
      when: "'notification_templates' in input_tag or 'all' in input_tag"
    - name: "Export Users"
      ansible.builtin.include_tasks: "users.yml"
      when: "'users' in input_tag or 'all' in input_tag"
    - name: "Export Teams"
      ansible.builtin.include_tasks: "teams.yml"
      when: "'teams' in input_tag or 'all' in input_tag"
    - name: "Export Organizations"
      ansible.builtin.include_tasks: "organizations.yml"
      when: "'organizations' in input_tag or 'all' in input_tag"
    - name: "Export Job Templates"
      ansible.builtin.include_tasks: "job_templates.yml"
      when: "'job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Projects"
      ansible.builtin.include_tasks: "projects.yml"
      when: "'projects' in input_tag or 'all' in input_tag"
    - name: "Export Execution Environments"
      ansible.builtin.include_tasks: "execution_environments.yml"
      when: "('execution_environments' in input_tag or 'all' in input_tag) and is_aap"
    - name: "Export Workflow Job Templates"
      ansible.builtin.include_tasks: "workflow_job_templates.yml"
      when: "'workflow_job_templates' in input_tag or 'all' in input_tag"
    - name: "Export Settings"
      ansible.builtin.include_tasks: "settings.yml"
      when: "'settings' in input_tag or 'all' in input_tag"
    - name: "Export Instance Groups"
      ansible.builtin.include_tasks: "instance_groups.yml"
      when: "'instance_groups' in input_tag or 'all' in input_tag"
    - name: "Export Applications"
      ansible.builtin.include_tasks: "applications.yml"
      when: "'applications' in input_tag or 'all' in input_tag"
    - name: "Export Labels"
      ansible.builtin.include_tasks: "labels.yml"
      when: "'labels' in input_tag or 'all' in input_tag"
...
