---
- name: "Get current Applications from the API"
  ansible.builtin.set_fact:
    applications_lookvar: "{{ query(controller_api_plugin, 'api/v2/applications/',
                                query_params={'order_by': 'organization,id'},
                                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                return_all=true, max_objects=query_controller_api_max_objects)
                           }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the <ORGANIZATION_NAME>/applications output directory for applications in {{ output_path }}"
  ansible.builtin.file:
    path: "{{ __path }}"
    state: directory
    mode: '0755'
  vars:
    __path: "{{ output_path }}/{{ needed_path | regex_replace('/', '_') }}/applications"
  loop: "{{ (applications_lookvar | map(attribute='summary_fields') | selectattr('organization', 'defined') | map(attribute='organization') | map(attribute='name') | list | flatten | unique)
            + (['ORGANIZATIONLESS'] if ((applications_lookvar | map(attribute='summary_fields') | selectattr('organization', 'undefined') | list | flatten) | length > 0) else [])
         }}"
  loop_control:
    loop_var: needed_path
    label: "{{ __path }}"

- name: "Add current applications to the <ORGANIZATION_NAME>/applications output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/current_applications.j2"
    dest: "{{ __dest }}"
    mode: '0644'
  vars:
    application_organization: "{{ current_applications_asset_value.summary_fields.organization.name | default('ORGANIZATIONLESS', true) }}"
    application_id: "{{ current_applications_asset_value.id }}"
    application_name: "{{ current_applications_asset_value.name | regex_replace('/', '_') }}"
    __dest: "{{ output_path }}/{{ application_organization | regex_replace('/', '_') }}/applications/{{ application_id }}_{{ application_name | regex_replace('/', '_') }}.yaml"
  loop: "{{ applications_lookvar }}"
  loop_control:
    loop_var: current_applications_asset_value
    label: "{{ __dest }}"
...
