---
- name: "Create the output directory for groups: {{ groups_output_path }}"
  ansible.builtin.file:
    path: "{{ groups_output_path }}"
    state: directory
    mode: '0755'

- name: "Add current groups to the current_groups.yaml output file in {{ groups_output_path }}"
  ansible.builtin.template:
    src: "templates/current_groups.j2"
    dest: "{{ groups_output_path }}/current_groups.yaml"
    mode: '0644'
  when: current_groups_asset_value | length > 0
...
