---
- name: "Create the output directory for hosts: {{ hosts_output_path }}"
  ansible.builtin.file:
    path: "{{ hosts_output_path }}"
    state: directory
    mode: '0755'

- name: "Add current hosts to the current_hosts.yaml output file in {{ hosts_output_path }}"
  ansible.builtin.template:
    src: "templates/current_hosts.j2"
    dest: "{{ hosts_output_path }}/current_hosts.yaml"
    mode: '0644'
  when: current_hosts_asset_value | length > 0
...
