---
- name: "Get current Instance Groups from the API"
  ansible.builtin.set_fact:
    instance_groups_lookvar: "{{ query(controller_api_plugin, 'api/v2/instance_groups/',
                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                              return_all=true, max_objects=query_controller_api_max_objects)
                                     }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for instance groups: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current instance groups to the current_instance_groups.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/current_instance_groups.j2"
    dest: "{{ output_path }}/current_instance_groups.yaml"
    mode: '0644'
  vars:
    current_instance_groups_asset_value: "{{ instance_groups_lookvar }}"
...
