---
- name: "Get current Notification Templates from the API"
  ansible.builtin.set_fact:
    notification_templates_lookvar: "{{ query(controller_api_plugin, 'api/v2/notification_templates/',
                                              host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                              return_all=true, max_objects=query_controller_api_max_objects)
                                     }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the <ORGANIZATION_NAME>/notification_templates output directory for notification templates in {{ output_path }}"
  ansible.builtin.file:
    path: "{{ __path }}"
    state: directory
    mode: '0755'
  vars:
    __path: "{{ output_path }}/{{ needed_path | regex_replace('/', '_') }}/notification_templates"
  loop: "{{ (notification_templates_lookvar | map(attribute='summary_fields') | selectattr('organization', 'defined') | map(attribute='organization') | map(attribute='name') | list | flatten | unique)
            + (['ORGANIZATIONLESS'] if ((notification_templates_lookvar | map(attribute='summary_fields') | selectattr('organization', 'undefined') | list | flatten) | length > 0) else [])
         }}"
  loop_control:
    loop_var: needed_path
    label: "{{ __path }}"

- name: "Add current notification templates to the <ORGANIZATION_NAME>/current_notification_templates.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/current_notification_templates.j2"
    dest: "{{ __dest }}"
    mode: '0644'
  vars:
    __dest: "{{ output_path }}/{{ (current_notification_templates_asset_value.summary_fields.organization.name | default('ORGANIZATIONLESS', true)) | regex_replace('/', '_') }}/notification_templates/{{ current_notification_templates_asset_value.name | regex_replace('/', '_') }}.yaml"
  loop: "{{ notification_templates_lookvar }}"
  loop_control:
    loop_var: current_notification_templates_asset_value
    label: "{{ __dest }}"
...
