---
- name: "Get current Users from the API"
  ansible.builtin.set_fact:
    user_roles_lookvar: "{{ query(controller_api_plugin, 'api/v2/users/' + (username | urlencode()) + '/roles/',
                                  host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                  return_all=true, max_objects=query_controller_api_max_objects)
                         }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for user roles: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}/user_roles"
    state: directory
    mode: '0755'

- name: "Add current roles to the output yaml file"
  ansible.builtin.template:
    src: "templates/current_user_roles.j2"
    dest: "{{ output_path }}/user_roles/current_roles_{{ username | regex_replace('/', '_') }}.yaml"
    mode: '0644'
  vars:
    current_user_roles_asset_value: "{{ user_roles_lookvar }}"
  when: user_roles_lookvar | length > 0
...
