download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/amazon-aws-5.2.0.tar.gz
format_version: 1.0.0
name: aws
namespace: amazon
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2023-01-24T14:35:48.030359Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIVAwUAY8/sweGkvXCKgoqtAQhAhQ/+JbwADbE+v7VY0ATl7NUZX6Xr8Ro/Mb5A

    yPt4u7f/1dEDRaulHs8Qpkd+loA6HBsGbrcmKVsf2opra+4oWGyZypgqgFtS/EZl

    hgYqSL5inmC+0Cgh/AOsdg0QuI4lMVDga5p1mwOTfYgX7PD+eAA8CVQV06IIuH+Q

    aRh5ev5Fh1QJf7FB3mXcd0qEV7W4fiIjlxG/ug6YEHUV0rfItpErpQEbbF17Rrr4

    oY7E+fZoAaIxejfzbPy2qK8b6c2ClIWCIreLECV0+WWrSt0dRseTVTft7W4gWUjx

    x0Axzt83fBJZhZdbp5MrWNI9KBXeT9GgzXu9wPHpQwWXeu8sVKQoJiE7ERwBbDue

    nU9wORtHZ49toWgUPiSERgkqQt0LU78WXlrRME6IZ7SKE+mMSc1rWh+tXgCmLFC9

    8NDJNbcC7DfYEr6H+t68mTFKJ3f4vmgCKjOzWNN5GOeayY+zlv7XtBqTUyq5lXv0

    iQnNoeS30MLfQXv4Mw4pqOq3aMZ+S/VnAzrGucs8okLleC4gWvs95lROFmdiXHgk

    EIUWSqrj99TXWrPN9epRBnX6UxNPpcF28jCw/HYPfrMjA1Jb4ftZIV6Xwr9lAhix

    h+h5aEaXR2RvsyfcOtj9mWFdLzUox4Uur9M1M7mN4/OumME2Wl9LB1Bh1lx2PwEd

    +14Ac1nBP6M=

    =yTm9

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 5.2.0
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/amazon/aws/versions/5.2.0/
