---
- name: Run compliance scan with Red Hat Insights
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    compliance_profile_configured: undef

  tasks:
    - name: Check OS Type
      ansible.builtin.assert:
        that: "ansible_os_family == 'RedHat'"

    - name: Check variable values
      ansible.builtin.debug:
        msg: "Value of compliance_profile_configured is {{ compliance_profile_configured }}"

    - name: Run Insights Compliance scan
      ansible.builtin.import_role:
        name: redhat.insights.compliance
      when: compliance_profile_configured == "Yes"

    - name: Notify user that Compliance scan is not being attempted
      ansible.builtin.debug:
        msg: "User has not confirmed that all hosts are associated with an Insights Compliance profile. Scan aborted."
      when: compliance_profile_configured == "No"
