---
- name: Stop service
  hosts: "{{ _hosts | default(omit) }}"
  become: true
  vars:
    service_name: undef

  tasks:
    - name: Check Service
      ansible.builtin.service_facts:

    - name: Stop Service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      when: service_name + '.service' in services
