download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-controller-4.3.0.tar.gz
format_version: 1.0.0
name: controller
namespace: ansible
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2022-11-17T18:51:27.365281Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIVAwUAY3aCreGkvXCKgoqtAQhnuA/+Pz8w7E88pAdZRDxFNhLSq18bhsxMmKfb

    QfxJUUHc7lpbjepN55VlU0UqZIhDrMztl9LphWp3dsayMGPL8vU0l7AH0jmKR9kw

    Fl+wXie+yr+5ZtG1BbrLFgVHhS0wnEHUYjxVTs9eHJDEm96JBqJ9BgeRHSQFPMzG

    N3QS8MtIaiAAMQeNySpdi8sOKSeeoKOxjPAxEBgJWhBtEIEbWgu2K61HqHso89Lj

    nSULiX8tRAHAAciY1OHAX4Oecnb1htK/a66vBI4a46Nf/jftx++ZQJJNxIEqGQGR

    pz+G3RezLwoGQPAj4dWy8tsIL18Umebjtt8AGtHoAoV11MRMh2pe5IQbN+HJKER7

    P9Lc3FsUtV/VL1z0A1kv63Xj9ii7ksG+Pd+dB0+SfD8ieFJBYIIwWXjsNdxY1EPs

    3EZigbt1I1ThL8Edd/E6lgsUL4awzX8lHeVcmRaPbHrGLuJrRHXEvn86zSq0rTR5

    nJK2HChQMTOKyMv1WvMhwktHok8V0ZMqAaavMYQcHZmqDuGlV+QS8/Vd4+gShucR

    xVZjVXqMlZS6Fbq/niadRIW5ch2s4ZpJkN0dhAItMdY0Lu9KPKLwoD5JuC9eziB4

    ZNk56UJ04MGkrg2SPxvDxZkGgNncAqkfqoFLQYawI73rwyARR2ZPLrAHA7EVnRBI

    gcdAOAbDsLY=

    =icJe

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 4.3.0
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/ansible/controller/versions/4.3.0/
